// Copyright (c) University of Washington 2026. Licensed under the MIT License.

using System;
using System.Collections.Generic;
using System.IO;
using System.Security.Cryptography;
using System.Text.Json;
using pwiz.Osprey.ML;
using Xunit;

namespace MARS.Test;

/// <summary>
/// Drift guard for the vendored Osprey.ML sources. Osprey.ML owns this code; MARS carries a
/// copy only because pwiz has no package feed yet. These tests turn an accidental local edit
/// into a visible failure instead of a silent fork.
/// </summary>
public sealed class VendoredOspreyTest
{
    [Fact]
    public void VendoredFilesMatchRecordedHashes()
    {
        string vendorDirectory = TestPaths.VendoredOspreyDirectory;
        string manifestPath = Path.Combine(vendorDirectory, "UPSTREAM.json");
        Assert.True(File.Exists(manifestPath), $"Missing drift-guard manifest: {manifestPath}");

        using JsonDocument manifest = JsonDocument.Parse(File.ReadAllText(manifestPath));
        JsonElement files = manifest.RootElement.GetProperty("files");

        var checkedAny = false;
        foreach (JsonElement file in files.EnumerateArray())
        {
            string name = file.GetProperty("vendored").GetString()!;
            string expected = file.GetProperty("sha256").GetString()!;
            string path = Path.Combine(vendorDirectory, name);

            Assert.True(File.Exists(path), $"Vendored file is missing: {path}");

            using FileStream stream = File.OpenRead(path);
            string actual = Convert.ToHexString(SHA256.HashData(stream));

            Assert.True(
                string.Equals(expected, actual, StringComparison.OrdinalIgnoreCase),
                $"Vendored {name} no longer matches its recorded hash.\n" +
                $"  recorded {expected}\n  actual   {actual}\n" +
                "Do not edit vendored sources. Fix it upstream in pwiz, then run " +
                "scripts/sync-osprey-ml.ps1 -Apply.");

            checkedAny = true;
        }

        Assert.True(checkedAny, "The manifest listed no files to check.");
    }

    /// <summary>
    /// XorShift64 is vendored as a fragment rather than a whole file, so its guard is the
    /// sequence it produces rather than a text hash. Reformatting upstream is harmless; a
    /// change to the shift constants would break every seeded result in Osprey and MARS.
    /// </summary>
    [Fact]
    public void XorShift64ProducesTheUpstreamSequence()
    {
        var rng = new XorShift64(42);
        var actual = new ulong[8];
        for (var i = 0; i < actual.Length; i++) actual[i] = rng.Next();

        // Generated by the reference implementation in
        // pwiz_tools/Osprey/Osprey.ML/LinearSvmClassifier.cs.
        ulong[] expected = Reference(42, actual.Length);
        Assert.Equal(expected, actual);

        // A zero seed must not collapse the generator to a fixed point.
        var zeroSeeded = new XorShift64(0);
        Assert.NotEqual(0UL, zeroSeeded.Next());
    }

    private static ulong[] Reference(ulong seed, int count)
    {
        ulong state = seed == 0 ? 1UL : seed;
        var values = new ulong[count];
        for (var i = 0; i < count; i++)
        {
            ulong x = state;
            x ^= x << 13;
            x ^= x >> 7;
            x ^= x << 17;
            state = x;
            values[i] = x;
        }

        return values;
    }

    /// <summary>
    /// The regression objective must fit a continuous target and stay reproducible. This is
    /// the MARS-side mirror of the Osprey.Test case, so a bad vendor sync fails here too.
    /// </summary>
    [Fact]
    public void SquaredErrorObjectiveFitsAndReproduces()
    {
        var x = new double[200][];
        var y = new double[200];
        for (var i = 0; i < x.Length; i++)
        {
            x[i] = new[] { i * 0.05, (i % 5) * 1.1, ((i * 7) % 13) * 0.3 };
            y[i] = (0.4 * x[i][0]) - (0.15 * x[i][2]) + 2.0;
        }

        var parameters = new GbtParams
        {
            Objective = GbtObjective.SquaredError,
            NTrees = 60,
            MaxDepth = 5,
            Subsample = 1.0,
            ColSample = 1.0,
            MaxBins = 128,
            Seed = 42,
        };

        var first = GradientBoostedTrees.Train(x, y, parameters);
        var second = GradientBoostedTrees.Train(x, y, parameters);

        double sse = 0, baseline = 0, mean = 0;
        foreach (double value in y) mean += value;
        mean /= y.Length;

        for (var i = 0; i < x.Length; i++)
        {
            double score = first.ScoreSingle(x[i]);
            Assert.Equal(score, second.ScoreSingle(x[i]));
            sse += (y[i] - score) * (y[i] - score);
            baseline += (y[i] - mean) * (y[i] - mean);
        }

        Assert.True(sse < 0.02 * baseline, $"squared error {sse} should be far below the baseline {baseline}");
    }

    [Fact]
    public void ModelDataRoundTripsExactly()
    {
        var x = new double[120][];
        var y = new double[120];
        for (var i = 0; i < x.Length; i++)
        {
            x[i] = new[] { (i % 11) * 0.4, i * 0.02 };
            y[i] = (0.25 * x[i][0]) - (0.1 * x[i][1]);
        }

        var parameters = new GbtParams
        {
            Objective = GbtObjective.SquaredError,
            NTrees = 25,
            MaxDepth = 4,
            Subsample = 1.0,
            ColSample = 1.0,
            Seed = 7,
        };

        var model = GradientBoostedTrees.Train(x, y, parameters);
        var reloaded = GradientBoostedTrees.FromModelData(model.ToModelData());

        foreach (double[] row in x) Assert.Equal(model.ScoreSingle(row), reloaded.ScoreSingle(row));
    }
}

internal static class TestPaths
{
    /// <summary>Walks up from the test binary to the dotnet solution directory.</summary>
    public static string SolutionDirectory
    {
        get
        {
            var directory = new DirectoryInfo(AppContext.BaseDirectory);
            while (directory is not null)
            {
                if (File.Exists(Path.Combine(directory.FullName, "MARS.sln"))) return directory.FullName;
                directory = directory.Parent;
            }

            throw new DirectoryNotFoundException("Could not locate MARS.sln above the test binary.");
        }
    }

    public static string VendoredOspreyDirectory =>
        Path.Combine(SolutionDirectory, "third_party", "Osprey.ML");

    /// <summary>The repository root, one level above the dotnet solution.</summary>
    public static string RepositoryRoot => Directory.GetParent(SolutionDirectory)!.FullName;

    /// <summary>Example data, when it is present. These files are not in source control.</summary>
    public static bool TryFindExampleFile(string relativePath, out string fullPath)
    {
        fullPath = Path.Combine(RepositoryRoot, relativePath);
        return File.Exists(fullPath);
    }
}
